# Generated by Django 5.2.1 on 2025-06-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('game_type', models.CharField(choices=[('Game', 'Game'), ('of', 'Of'), ('x', 'X')], max_length=10)),
                ('game_mode', models.CharField(choices=[('PvAi', 'Pvai')], max_length=10)),
                ('status', models.CharField(choices=[('Game', 'Game'), ('started', 'Started')], max_length=10)),
                ('ai_model', models.CharField(blank=True, choices=[('MCTS', 'Mcts')], max_length=11, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
