# Generated by Django 5.2.1 on 2025-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('RL', 'RL'), ('MCTS', 'MCTS'), ('HARD_CODED', 'Hard Coded')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('PVP', 'PvP'), ('PVAI', 'PvAi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('GAME_OF_X', 'Game of x'), ('HARD', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for opponent'), ('ACTIVE', 'Game started'), ('FINISHED', 'Game finished')], max_length=10),
        ),
    ]
