# Generated by Django 5.2.1 on 2025-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_board_game_creator_point_game_opponent_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator_cards',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_cards',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
