# Generated by Django 5.2.1 on 2025-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_creator_cards_game_opponent_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_cards',
            field=models.CharField(default='[]', max_length=11),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_cards',
            field=models.CharField(default='[]', max_length=11),
        ),
    ]
