# Generated by Django 5.2.1 on 2025-07-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_game_surrendered_by_game_winner_alter_game_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('PvP', 'PvP'), ('PvAI', 'PvAi')], max_length=10),
        ),
    ]
