# Generated by Django 5.2.1 on 2025-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_game_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('PvP', 'PvP'), ('PvAi', 'PvAi')], max_length=10),
        ),
    ]
