# Generated by Django 5.2.1 on 2025-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('RL', 'RL'), ('MCTS', 'MCTS'), ('Hard_coded', 'Hard_coded')], max_length=11, null=True),
        ),
    ]
