# Generated by Django 5.2.1 on 2025-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_game_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('RL', 'RL'), ('MCTS', 'MCTS'), ('Hard coded', 'Hard coded')], max_length=11, null=True),
        ),
    ]
