# Generated by Django 5.2.1 on 2025-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_game_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.CharField(default='0000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x', max_length=200),
        ),
    ]
