# Generated by Django 5.2.1 on 2025-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_game_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='pool',
            field=models.CharField(default='01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x+-/x', max_length=300),
        ),
    ]
