# Generated by Django 5.2.1 on 2026-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_game_tie_alter_game_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('SINGLE_CARD', 'Single Card'), ('HARD', 'Hard')], max_length=12),
        ),
    ]
